name: Status-Vercel

on:
  push:
    branches: [ "source"]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'npm'
      env:
        CI: true
    - name: Install
      run: |
        npm install yarn -g
        yarn config set "strict-ssl" false -g
        yarn
    - name: Clone deploy branch
      run: |
        REMOTE_BRANCH="${REMOTE_BRANCH:-public}"
        REMOTE_REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        rm -rf dist
        mkdir -p dist

        git clone --depth=1 --branch="${REMOTE_BRANCH}" --single-branch --no-checkout \
          "${REMOTE_REPO}" dist
    - name: Build
      run: yarn build
    - name: Deploy to GitHub Pages
      if: "github.event_name == 'push'"
      run: |
        SOURCE_COMMIT="$(git log -1 --pretty="%an: %B" "$GITHUB_SHA")"
        pushd dist &>/dev/null
 
        : > .nojekyll
        git add --all

        if [ "$(git status --porcelain | wc -l)" -eq 0 ]; then
          exit 0
        fi
        git -c user.name="GitHub" -c user.email="noreply@github.com" \
          commit --quiet \
          --message "Deploy from ${GITHUB_SHA}" \
          --message "$SOURCE_COMMIT"
        git push

        popd &>/dev/null
